version: '3.8'
services:
  db:
    image: postgis/postgis:15-3.4
    container_name: blood-postgis
    environment:
      - POSTGRES_DB=blooddb
      - POSTGRES_USER=blooduser
      - POSTGRES_PASSWORD=bloodpwd
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/initdb:/docker-entrypoint-initdb.d:ro
volumes:
  db_data: